services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: aws_try_out
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d aws_try_out"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    profiles: [containerized]  # Don't start it by default
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      USE_IN_MEMORY_DB: "false"
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/aws_try_out
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
